### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by pratikmallya** [spotify/gimme#10]
Was thinking of deploying this but it seems like its not been updated in a long long time, wondering if this is not being developed on anymore?

**Comment by cschnei3** [comment]
So IAM Conditions https://cloud.google.com/iam/docs/conditions-overview that this depends on is still in private beta. You can also only whitelist specific projects. So we have not been putting time into this until this is out of private beta and we can whitelist our entire organization. We found it not so useful for only a few whitelisted projects.

**Comment by pratikmallya** [comment]
Aw, that sucks. Sounds like you've been waiting for a long time.

**Comment by cschnei3** [comment]
Yeah since Google Next SF 2018, but hopefully it will be GA soon!
