### ISSUE TITLE
Local Development - Redirect Loop

### ISSUE THREAD

**Issue by alexcurtin** [spotify/gimme#9]
I've followed the configuration setup and set my oauth consent screen / redirects up for localhost development but after the google OAUTH screen logs in I get redirected back to the /login/google screen. Any ideas? Thanks!

**Comment by cschnei3** [comment]
Hmm, I am getting the open redirect loop now also. We had this problem when we were developing it and then fixed it and now I do not know why it is  back. Ill look into it when I have a chance.

**Comment by alexcurtin** [comment]
Thanks for taking a look @cschnei3 !

**Comment by alexcurtin** [comment]
@cschnei3 any hints where to start looking for ourselves?

**Comment by justinholmes** [comment]
I've tracked it down to the google_oauth_state not being set 
`        state_key = "{bp.name}_oauth_state".format(bp=self)
        if state_key not in flask.session:
            # can't validate state, so redirect back to login view
            log.info("state not found, redirecting user to login")
            return redirect(url_for(".login"))`
in flask dance
this then causes it to redirect constantly to the root.

**Comment by justinholmes** [comment]
I think it might be the browser not setting a flask cookie for localhost or 127.0.0.1

**Comment by justinholmes** [comment]
Got it working locally with flask run --cert ~/{cert} --key ~/{key} and setting an override in /etc/hosts

**Comment by mspringare** [comment]
This is resolved in https://github.com/spotify/gimme/pull/11

By setting `GIMME_DEV=true` for local development it will work without SSL and there will be no redirect loops.
